/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/work/hdl/synth_top.sv:6.1-49.10" *)
module compute_core(clk, rst, activation, act_valid, weight_row, weight_valid, out, result_valid);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  (* src = "/work/hdl/synth_top.sv:13.31-13.40" *)
  input act_valid;
  wire act_valid;
  (* src = "/work/hdl/synth_top.sv:12.31-12.41" *)
  input [63:0] activation;
  wire [63:0] activation;
  (* src = "/work/hdl/synth_top.sv:9.31-9.34" *)
  input clk;
  wire clk;
  (* src = "/work/hdl/synth_top.sv:18.31-18.34" *)
  output out;
  wire out;
  (* src = "/work/hdl/synth_top.sv:19.31-19.43" *)
  output result_valid;
  wire result_valid;
  (* src = "/work/hdl/synth_top.sv:10.31-10.34" *)
  input rst;
  wire rst;
  (* src = "/work/hdl/synth_top.sv:15.31-15.41" *)
  input [63:0] weight_row;
  wire [63:0] weight_row;
  (* src = "/work/hdl/synth_top.sv:16.31-16.43" *)
  input weight_valid;
  wire weight_valid;
  sky130_fd_sc_hd__nand2_1 _257_ (
    .A(weight_valid),
    .B(act_valid),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _258_ (
    .A(rst),
    .B(_002_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__xnor2_4 _259_ (
    .A(weight_row[1]),
    .B(activation[1]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__xnor2_4 _260_ (
    .A(weight_row[0]),
    .B(activation[0]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__xor2_1 _261_ (
    .A(weight_row[3]),
    .B(activation[3]),
    .X(_005_)
  );
  sky130_fd_sc_hd__xnor3_1 _262_ (
    .A(_003_),
    .B(_004_),
    .C(_005_),
    .X(_006_)
  );
  sky130_fd_sc_hd__xor2_1 _263_ (
    .A(weight_row[62]),
    .B(activation[62]),
    .X(_007_)
  );
  sky130_fd_sc_hd__xnor2_1 _264_ (
    .A(weight_row[7]),
    .B(activation[7]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(weight_row[5]),
    .B(activation[5]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xnor2_1 _266_ (
    .A(weight_row[9]),
    .B(activation[9]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__xor3_1 _267_ (
    .A(_008_),
    .B(_009_),
    .C(_010_),
    .X(_011_)
  );
  sky130_fd_sc_hd__xnor3_1 _268_ (
    .A(_006_),
    .B(_007_),
    .C(_011_),
    .X(_012_)
  );
  sky130_fd_sc_hd__xor2_1 _269_ (
    .A(weight_row[40]),
    .B(activation[40]),
    .X(_013_)
  );
  sky130_fd_sc_hd__xor2_2 _270_ (
    .A(weight_row[13]),
    .B(activation[13]),
    .X(_014_)
  );
  sky130_fd_sc_hd__xor2_1 _271_ (
    .A(weight_row[11]),
    .B(activation[11]),
    .X(_015_)
  );
  sky130_fd_sc_hd__xor2_1 _272_ (
    .A(weight_row[15]),
    .B(activation[15]),
    .X(_016_)
  );
  sky130_fd_sc_hd__xor3_1 _273_ (
    .A(_014_),
    .B(_015_),
    .C(_016_),
    .X(_017_)
  );
  sky130_fd_sc_hd__xor2_1 _274_ (
    .A(weight_row[60]),
    .B(activation[60]),
    .X(_018_)
  );
  sky130_fd_sc_hd__xor2_1 _275_ (
    .A(weight_row[58]),
    .B(activation[58]),
    .X(_019_)
  );
  sky130_fd_sc_hd__xnor3_1 _276_ (
    .A(_017_),
    .B(_018_),
    .C(_019_),
    .X(_020_)
  );
  sky130_fd_sc_hd__xnor3_1 _277_ (
    .A(_012_),
    .B(_013_),
    .C(_020_),
    .X(_021_)
  );
  sky130_fd_sc_hd__xor2_1 _278_ (
    .A(weight_row[26]),
    .B(activation[26]),
    .X(_022_)
  );
  sky130_fd_sc_hd__xor2_2 _279_ (
    .A(weight_row[19]),
    .B(activation[19]),
    .X(_023_)
  );
  sky130_fd_sc_hd__xor2_1 _280_ (
    .A(weight_row[17]),
    .B(activation[17]),
    .X(_024_)
  );
  sky130_fd_sc_hd__xor2_1 _281_ (
    .A(weight_row[21]),
    .B(activation[21]),
    .X(_025_)
  );
  sky130_fd_sc_hd__xor3_1 _282_ (
    .A(_023_),
    .B(_024_),
    .C(_025_),
    .X(_026_)
  );
  sky130_fd_sc_hd__xor2_1 _283_ (
    .A(weight_row[56]),
    .B(activation[56]),
    .X(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _284_ (
    .A(weight_row[25]),
    .B(activation[25]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__xnor2_1 _285_ (
    .A(weight_row[23]),
    .B(activation[23]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xnor2_1 _286_ (
    .A(weight_row[27]),
    .B(activation[27]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xnor3_1 _287_ (
    .A(_028_),
    .B(_029_),
    .C(_030_),
    .X(_031_)
  );
  sky130_fd_sc_hd__xor3_1 _288_ (
    .A(_026_),
    .B(_027_),
    .C(_031_),
    .X(_032_)
  );
  sky130_fd_sc_hd__xor2_1 _289_ (
    .A(weight_row[38]),
    .B(activation[38]),
    .X(_033_)
  );
  sky130_fd_sc_hd__xor2_1 _290_ (
    .A(weight_row[36]),
    .B(activation[36]),
    .X(_034_)
  );
  sky130_fd_sc_hd__xnor3_1 _291_ (
    .A(_032_),
    .B(_033_),
    .C(_034_),
    .X(_035_)
  );
  sky130_fd_sc_hd__xnor3_1 _292_ (
    .A(_021_),
    .B(_022_),
    .C(_035_),
    .X(_036_)
  );
  sky130_fd_sc_hd__xor2_1 _293_ (
    .A(weight_row[16]),
    .B(activation[16]),
    .X(_037_)
  );
  sky130_fd_sc_hd__xor2_2 _294_ (
    .A(weight_row[31]),
    .B(activation[31]),
    .X(_038_)
  );
  sky130_fd_sc_hd__xor2_1 _295_ (
    .A(weight_row[29]),
    .B(activation[29]),
    .X(_039_)
  );
  sky130_fd_sc_hd__xor2_1 _296_ (
    .A(weight_row[33]),
    .B(activation[33]),
    .X(_040_)
  );
  sky130_fd_sc_hd__xor3_1 _297_ (
    .A(_038_),
    .B(_039_),
    .C(_040_),
    .X(_041_)
  );
  sky130_fd_sc_hd__xor2_1 _298_ (
    .A(weight_row[54]),
    .B(activation[54]),
    .X(_042_)
  );
  sky130_fd_sc_hd__xor2_1 _299_ (
    .A(weight_row[52]),
    .B(activation[52]),
    .X(_043_)
  );
  sky130_fd_sc_hd__xor3_1 _300_ (
    .A(_041_),
    .B(_042_),
    .C(_043_),
    .X(_044_)
  );
  sky130_fd_sc_hd__xor2_1 _301_ (
    .A(weight_row[34]),
    .B(activation[34]),
    .X(_045_)
  );
  sky130_fd_sc_hd__xor2_1 _302_ (
    .A(weight_row[37]),
    .B(activation[37]),
    .X(_046_)
  );
  sky130_fd_sc_hd__xor2_1 _303_ (
    .A(weight_row[35]),
    .B(activation[35]),
    .X(_047_)
  );
  sky130_fd_sc_hd__xor2_1 _304_ (
    .A(weight_row[39]),
    .B(activation[39]),
    .X(_048_)
  );
  sky130_fd_sc_hd__xor3_1 _305_ (
    .A(_046_),
    .B(_047_),
    .C(_048_),
    .X(_049_)
  );
  sky130_fd_sc_hd__xor2_1 _306_ (
    .A(weight_row[50]),
    .B(activation[50]),
    .X(_050_)
  );
  sky130_fd_sc_hd__xor2_1 _307_ (
    .A(weight_row[43]),
    .B(activation[43]),
    .X(_051_)
  );
  sky130_fd_sc_hd__xnor2_2 _308_ (
    .A(weight_row[41]),
    .B(activation[41]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__xor2_1 _309_ (
    .A(weight_row[45]),
    .B(activation[45]),
    .X(_053_)
  );
  sky130_fd_sc_hd__xnor3_1 _310_ (
    .A(_051_),
    .B(_052_),
    .C(_053_),
    .X(_054_)
  );
  sky130_fd_sc_hd__xor3_1 _311_ (
    .A(_049_),
    .B(_050_),
    .C(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__xor3_1 _312_ (
    .A(_044_),
    .B(_045_),
    .C(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__xor2_1 _313_ (
    .A(weight_row[24]),
    .B(activation[24]),
    .X(_057_)
  );
  sky130_fd_sc_hd__xor2_1 _314_ (
    .A(weight_row[22]),
    .B(activation[22]),
    .X(_058_)
  );
  sky130_fd_sc_hd__xnor3_1 _315_ (
    .A(_056_),
    .B(_057_),
    .C(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__xnor3_1 _316_ (
    .A(_036_),
    .B(_037_),
    .C(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd__xor2_1 _317_ (
    .A(weight_row[10]),
    .B(activation[10]),
    .X(_061_)
  );
  sky130_fd_sc_hd__inv_1 _318_ (
    .A(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__xor2_1 _319_ (
    .A(weight_row[49]),
    .B(activation[49]),
    .X(_063_)
  );
  sky130_fd_sc_hd__xor2_1 _320_ (
    .A(weight_row[47]),
    .B(activation[47]),
    .X(_064_)
  );
  sky130_fd_sc_hd__xor2_1 _321_ (
    .A(weight_row[51]),
    .B(activation[51]),
    .X(_065_)
  );
  sky130_fd_sc_hd__xor3_1 _322_ (
    .A(_063_),
    .B(_064_),
    .C(_065_),
    .X(_066_)
  );
  sky130_fd_sc_hd__xor2_1 _323_ (
    .A(weight_row[48]),
    .B(activation[48]),
    .X(_067_)
  );
  sky130_fd_sc_hd__xor2_1 _324_ (
    .A(weight_row[46]),
    .B(activation[46]),
    .X(_068_)
  );
  sky130_fd_sc_hd__xnor3_1 _325_ (
    .A(_066_),
    .B(_067_),
    .C(_068_),
    .X(_069_)
  );
  sky130_fd_sc_hd__xor2_1 _326_ (
    .A(weight_row[32]),
    .B(activation[32]),
    .X(_070_)
  );
  sky130_fd_sc_hd__inv_1 _327_ (
    .A(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__xor2_1 _328_ (
    .A(weight_row[30]),
    .B(activation[30]),
    .X(_072_)
  );
  sky130_fd_sc_hd__xnor3_1 _329_ (
    .A(_069_),
    .B(_071_),
    .C(_072_),
    .X(_073_)
  );
  sky130_fd_sc_hd__xor2_1 _330_ (
    .A(weight_row[20]),
    .B(activation[20]),
    .X(_074_)
  );
  sky130_fd_sc_hd__inv_1 _331_ (
    .A(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__xor2_1 _332_ (
    .A(weight_row[55]),
    .B(activation[55]),
    .X(_076_)
  );
  sky130_fd_sc_hd__xor2_1 _333_ (
    .A(weight_row[53]),
    .B(activation[53]),
    .X(_077_)
  );
  sky130_fd_sc_hd__xor2_1 _334_ (
    .A(weight_row[57]),
    .B(activation[57]),
    .X(_078_)
  );
  sky130_fd_sc_hd__xor3_1 _335_ (
    .A(_076_),
    .B(_077_),
    .C(_078_),
    .X(_079_)
  );
  sky130_fd_sc_hd__xor2_1 _336_ (
    .A(weight_row[44]),
    .B(activation[44]),
    .X(_080_)
  );
  sky130_fd_sc_hd__xor2_1 _337_ (
    .A(weight_row[59]),
    .B(activation[59]),
    .X(_081_)
  );
  sky130_fd_sc_hd__xor2_1 _338_ (
    .A(weight_row[61]),
    .B(activation[61]),
    .X(_082_)
  );
  sky130_fd_sc_hd__xor2_1 _339_ (
    .A(weight_row[63]),
    .B(activation[63]),
    .X(_083_)
  );
  sky130_fd_sc_hd__xor3_1 _340_ (
    .A(_081_),
    .B(_082_),
    .C(_083_),
    .X(_084_)
  );
  sky130_fd_sc_hd__xor3_1 _341_ (
    .A(_079_),
    .B(_080_),
    .C(_084_),
    .X(_085_)
  );
  sky130_fd_sc_hd__xor2_1 _342_ (
    .A(weight_row[28]),
    .B(activation[28]),
    .X(_086_)
  );
  sky130_fd_sc_hd__xor2_1 _343_ (
    .A(weight_row[42]),
    .B(activation[42]),
    .X(_087_)
  );
  sky130_fd_sc_hd__xnor3_1 _344_ (
    .A(_085_),
    .B(_086_),
    .C(_087_),
    .X(_088_)
  );
  sky130_fd_sc_hd__xnor3_1 _345_ (
    .A(_073_),
    .B(_075_),
    .C(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd__xor2_1 _346_ (
    .A(weight_row[14]),
    .B(activation[14]),
    .X(_090_)
  );
  sky130_fd_sc_hd__xor2_1 _347_ (
    .A(weight_row[12]),
    .B(activation[12]),
    .X(_091_)
  );
  sky130_fd_sc_hd__xnor3_1 _348_ (
    .A(_089_),
    .B(_090_),
    .C(_091_),
    .X(_092_)
  );
  sky130_fd_sc_hd__xnor3_1 _349_ (
    .A(_060_),
    .B(_062_),
    .C(_092_),
    .X(_093_)
  );
  sky130_fd_sc_hd__xor2_1 _350_ (
    .A(weight_row[6]),
    .B(activation[6]),
    .X(_094_)
  );
  sky130_fd_sc_hd__xor2_1 _351_ (
    .A(weight_row[8]),
    .B(activation[8]),
    .X(_095_)
  );
  sky130_fd_sc_hd__maj3_2 _352_ (
    .A(_093_),
    .B(_094_),
    .C(_095_),
    .X(_096_)
  );
  sky130_fd_sc_hd__maj3_2 _353_ (
    .A(_060_),
    .B(_062_),
    .C(_092_),
    .X(_097_)
  );
  sky130_fd_sc_hd__inv_1 _354_ (
    .A(_037_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__maj3_2 _355_ (
    .A(_036_),
    .B(_098_),
    .C(_059_),
    .X(_099_)
  );
  sky130_fd_sc_hd__inv_1 _356_ (
    .A(_022_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__maj3_2 _357_ (
    .A(_021_),
    .B(_100_),
    .C(_035_),
    .X(_101_)
  );
  sky130_fd_sc_hd__inv_1 _358_ (
    .A(_013_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__maj3_2 _359_ (
    .A(_012_),
    .B(_102_),
    .C(_020_),
    .X(_103_)
  );
  sky130_fd_sc_hd__inv_1 _360_ (
    .A(_007_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__maj3_2 _361_ (
    .A(_006_),
    .B(_104_),
    .C(_011_),
    .X(_105_)
  );
  sky130_fd_sc_hd__nor2_1 _362_ (
    .A(_003_),
    .B(_004_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _363_ (
    .A(_003_),
    .B(_004_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__o21ai_0 _364_ (
    .A1(_106_),
    .A2(_005_),
    .B1(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__maj3_1 _365_ (
    .A(_008_),
    .B(_009_),
    .C(_010_),
    .X(_109_)
  );
  sky130_fd_sc_hd__maj3_1 _366_ (
    .A(_014_),
    .B(_015_),
    .C(_016_),
    .X(_110_)
  );
  sky130_fd_sc_hd__xnor2_1 _367_ (
    .A(_109_),
    .B(_110_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__xor3_1 _368_ (
    .A(_105_),
    .B(_108_),
    .C(_111_),
    .X(_112_)
  );
  sky130_fd_sc_hd__maj3_1 _369_ (
    .A(_023_),
    .B(_024_),
    .C(_025_),
    .X(_113_)
  );
  sky130_fd_sc_hd__maj3_1 _370_ (
    .A(_017_),
    .B(_018_),
    .C(_019_),
    .X(_114_)
  );
  sky130_fd_sc_hd__maj3_1 _371_ (
    .A(_026_),
    .B(_027_),
    .C(_031_),
    .X(_115_)
  );
  sky130_fd_sc_hd__xnor3_1 _372_ (
    .A(_113_),
    .B(_114_),
    .C(_115_),
    .X(_116_)
  );
  sky130_fd_sc_hd__xor3_1 _373_ (
    .A(_103_),
    .B(_112_),
    .C(_116_),
    .X(_117_)
  );
  sky130_fd_sc_hd__maj3_1 _374_ (
    .A(_044_),
    .B(_045_),
    .C(_055_),
    .X(_118_)
  );
  sky130_fd_sc_hd__maj3_1 _375_ (
    .A(_041_),
    .B(_042_),
    .C(_043_),
    .X(_119_)
  );
  sky130_fd_sc_hd__maj3_1 _376_ (
    .A(_028_),
    .B(_029_),
    .C(_030_),
    .X(_120_)
  );
  sky130_fd_sc_hd__maj3_1 _377_ (
    .A(_038_),
    .B(_039_),
    .C(_040_),
    .X(_121_)
  );
  sky130_fd_sc_hd__xor2_1 _378_ (
    .A(_120_),
    .B(_121_),
    .X(_122_)
  );
  sky130_fd_sc_hd__maj3_1 _379_ (
    .A(_046_),
    .B(_047_),
    .C(_048_),
    .X(_123_)
  );
  sky130_fd_sc_hd__xor3_1 _380_ (
    .A(_119_),
    .B(_122_),
    .C(_123_),
    .X(_124_)
  );
  sky130_fd_sc_hd__maj3_1 _381_ (
    .A(_032_),
    .B(_033_),
    .C(_034_),
    .X(_125_)
  );
  sky130_fd_sc_hd__xnor3_1 _382_ (
    .A(_118_),
    .B(_124_),
    .C(_125_),
    .X(_126_)
  );
  sky130_fd_sc_hd__xor3_1 _383_ (
    .A(_101_),
    .B(_117_),
    .C(_126_),
    .X(_127_)
  );
  sky130_fd_sc_hd__maj3_1 _384_ (
    .A(_073_),
    .B(_075_),
    .C(_088_),
    .X(_128_)
  );
  sky130_fd_sc_hd__inv_1 _385_ (
    .A(_072_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__maj3_1 _386_ (
    .A(_069_),
    .B(_071_),
    .C(_129_),
    .X(_130_)
  );
  sky130_fd_sc_hd__xnor2_1 _387_ (
    .A(weight_row[43]),
    .B(activation[43]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__xnor2_1 _388_ (
    .A(weight_row[45]),
    .B(activation[45]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__maj3_1 _389_ (
    .A(_131_),
    .B(_052_),
    .C(_132_),
    .X(_133_)
  );
  sky130_fd_sc_hd__maj3_1 _390_ (
    .A(_063_),
    .B(_064_),
    .C(_065_),
    .X(_134_)
  );
  sky130_fd_sc_hd__xor2_1 _391_ (
    .A(_133_),
    .B(_134_),
    .X(_135_)
  );
  sky130_fd_sc_hd__maj3_1 _392_ (
    .A(_049_),
    .B(_050_),
    .C(_054_),
    .X(_136_)
  );
  sky130_fd_sc_hd__maj3_1 _393_ (
    .A(_066_),
    .B(_067_),
    .C(_068_),
    .X(_137_)
  );
  sky130_fd_sc_hd__xnor3_1 _394_ (
    .A(_135_),
    .B(_136_),
    .C(_137_),
    .X(_138_)
  );
  sky130_fd_sc_hd__maj3_1 _395_ (
    .A(_081_),
    .B(_082_),
    .C(_083_),
    .X(_139_)
  );
  sky130_fd_sc_hd__maj3_1 _396_ (
    .A(_079_),
    .B(_080_),
    .C(_084_),
    .X(_140_)
  );
  sky130_fd_sc_hd__maj3_1 _397_ (
    .A(_076_),
    .B(_077_),
    .C(_078_),
    .X(_141_)
  );
  sky130_fd_sc_hd__xnor3_1 _398_ (
    .A(_139_),
    .B(_140_),
    .C(_141_),
    .X(_142_)
  );
  sky130_fd_sc_hd__xor3_1 _399_ (
    .A(_130_),
    .B(_138_),
    .C(_142_),
    .X(_143_)
  );
  sky130_fd_sc_hd__maj3_1 _400_ (
    .A(_056_),
    .B(_057_),
    .C(_058_),
    .X(_144_)
  );
  sky130_fd_sc_hd__xnor3_1 _401_ (
    .A(_128_),
    .B(_143_),
    .C(_144_),
    .X(_145_)
  );
  sky130_fd_sc_hd__xor3_1 _402_ (
    .A(_099_),
    .B(_127_),
    .C(_145_),
    .X(_146_)
  );
  sky130_fd_sc_hd__maj3_1 _403_ (
    .A(_089_),
    .B(_090_),
    .C(_091_),
    .X(_147_)
  );
  sky130_fd_sc_hd__xnor3_1 _404_ (
    .A(_097_),
    .B(_146_),
    .C(_147_),
    .X(_148_)
  );
  sky130_fd_sc_hd__inv_1 _405_ (
    .A(_148_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__maj3_1 _406_ (
    .A(_085_),
    .B(_086_),
    .C(_087_),
    .X(_150_)
  );
  sky130_fd_sc_hd__maj3_1 _407_ (
    .A(_096_),
    .B(_149_),
    .C(_150_),
    .X(_151_)
  );
  sky130_fd_sc_hd__nor2_1 _408_ (
    .A(_140_),
    .B(_141_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__lpflow_inputiso0n_1 _409_ (
    .A(_140_),
    .SLEEP_B(_141_),
    .X(_153_)
  );
  sky130_fd_sc_hd__nor3_1 _410_ (
    .A(_139_),
    .B(_152_),
    .C(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _411_ (
    .A(_152_),
    .B(_154_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__inv_1 _412_ (
    .A(_147_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__maj3_2 _413_ (
    .A(_097_),
    .B(_146_),
    .C(_156_),
    .X(_157_)
  );
  sky130_fd_sc_hd__nand2b_1 _414_ (
    .A_N(_143_),
    .B(_144_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _415_ (
    .A(_143_),
    .SLEEP(_144_),
    .X(_159_)
  );
  sky130_fd_sc_hd__a21oi_1 _416_ (
    .A1(_128_),
    .A2(_158_),
    .B1(_159_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__maj3_1 _417_ (
    .A(_099_),
    .B(_127_),
    .C(_145_),
    .X(_161_)
  );
  sky130_fd_sc_hd__maj3_1 _418_ (
    .A(_101_),
    .B(_117_),
    .C(_126_),
    .X(_162_)
  );
  sky130_fd_sc_hd__maj3_1 _419_ (
    .A(_103_),
    .B(_112_),
    .C(_116_),
    .X(_163_)
  );
  sky130_fd_sc_hd__nand2_1 _420_ (
    .A(_105_),
    .B(_108_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__maj3_1 _421_ (
    .A(_105_),
    .B(_108_),
    .C(_111_),
    .X(_165_)
  );
  sky130_fd_sc_hd__inv_1 _422_ (
    .A(_110_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _423_ (
    .A(_109_),
    .B(_166_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__mux2_2 _424_ (
    .A0(_164_),
    .A1(_165_),
    .S(_167_),
    .X(_168_)
  );
  sky130_fd_sc_hd__inv_1 _425_ (
    .A(_121_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nand2_1 _426_ (
    .A(_120_),
    .B(_169_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__maj3_1 _427_ (
    .A(_113_),
    .B(_114_),
    .C(_115_),
    .X(_171_)
  );
  sky130_fd_sc_hd__maj3_1 _428_ (
    .A(_119_),
    .B(_122_),
    .C(_123_),
    .X(_172_)
  );
  sky130_fd_sc_hd__xnor3_1 _429_ (
    .A(_170_),
    .B(_171_),
    .C(_172_),
    .X(_173_)
  );
  sky130_fd_sc_hd__xor3_1 _430_ (
    .A(_163_),
    .B(_168_),
    .C(_173_),
    .X(_174_)
  );
  sky130_fd_sc_hd__xor2_1 _431_ (
    .A(_162_),
    .B(_174_),
    .X(_175_)
  );
  sky130_fd_sc_hd__maj3_1 _432_ (
    .A(_130_),
    .B(_138_),
    .C(_142_),
    .X(_176_)
  );
  sky130_fd_sc_hd__inv_1 _433_ (
    .A(_052_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__maj3_1 _434_ (
    .A(_051_),
    .B(_177_),
    .C(_053_),
    .X(_178_)
  );
  sky130_fd_sc_hd__nor2_1 _435_ (
    .A(_178_),
    .B(_134_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nor2_1 _436_ (
    .A(_135_),
    .B(_136_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nor2_1 _437_ (
    .A(_179_),
    .B(_180_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__and2_1 _438_ (
    .A(_135_),
    .B(_136_),
    .X(_182_)
  );
  sky130_fd_sc_hd__or3_1 _439_ (
    .A(_180_),
    .B(_182_),
    .C(_137_),
    .X(_183_)
  );
  sky130_fd_sc_hd__mux2i_1 _440_ (
    .A0(_179_),
    .A1(_181_),
    .S(_183_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__maj3_1 _441_ (
    .A(_118_),
    .B(_124_),
    .C(_125_),
    .X(_185_)
  );
  sky130_fd_sc_hd__xnor3_1 _442_ (
    .A(_176_),
    .B(_184_),
    .C(_185_),
    .X(_186_)
  );
  sky130_fd_sc_hd__xor3_1 _443_ (
    .A(_161_),
    .B(_175_),
    .C(_186_),
    .X(_187_)
  );
  sky130_fd_sc_hd__xnor3_2 _444_ (
    .A(_157_),
    .B(_160_),
    .C(_187_),
    .X(_188_)
  );
  sky130_fd_sc_hd__xnor2_1 _445_ (
    .A(_155_),
    .B(_188_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__xor2_1 _446_ (
    .A(_151_),
    .B(_189_),
    .X(_190_)
  );
  sky130_fd_sc_hd__xor3_1 _447_ (
    .A(_093_),
    .B(_094_),
    .C(_095_),
    .X(_191_)
  );
  sky130_fd_sc_hd__xor2_1 _448_ (
    .A(weight_row[4]),
    .B(activation[4]),
    .X(_192_)
  );
  sky130_fd_sc_hd__xor2_1 _449_ (
    .A(weight_row[18]),
    .B(activation[18]),
    .X(_193_)
  );
  sky130_fd_sc_hd__maj3_2 _450_ (
    .A(_191_),
    .B(_192_),
    .C(_193_),
    .X(_194_)
  );
  sky130_fd_sc_hd__xor3_1 _451_ (
    .A(_096_),
    .B(_148_),
    .C(_150_),
    .X(_195_)
  );
  sky130_fd_sc_hd__xnor2_4 _452_ (
    .A(_194_),
    .B(_195_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__xor3_1 _453_ (
    .A(_191_),
    .B(_192_),
    .C(_193_),
    .X(_197_)
  );
  sky130_fd_sc_hd__xor2_1 _454_ (
    .A(weight_row[2]),
    .B(activation[2]),
    .X(_198_)
  );
  sky130_fd_sc_hd__nor2_2 _455_ (
    .A(_197_),
    .B(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _456_ (
    .A(_195_),
    .SLEEP(_194_),
    .X(_200_)
  );
  sky130_fd_sc_hd__a21oi_2 _457_ (
    .A1(_196_),
    .A2(_199_),
    .B1(_200_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand2b_1 _458_ (
    .A_N(_151_),
    .B(_189_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__o21ai_2 _459_ (
    .A1(_190_),
    .A2(_201_),
    .B1(_202_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__xnor2_1 _460_ (
    .A(_160_),
    .B(_187_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nand2_1 _461_ (
    .A(_157_),
    .B(_204_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__o21ai_1 _462_ (
    .A1(_152_),
    .A2(_154_),
    .B1(_188_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__nand2_1 _463_ (
    .A(_205_),
    .B(_206_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__xor2_1 _464_ (
    .A(_175_),
    .B(_186_),
    .X(_208_)
  );
  sky130_fd_sc_hd__nor2_1 _465_ (
    .A(_161_),
    .B(_208_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nand2_1 _466_ (
    .A(_161_),
    .B(_208_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__o21ai_0 _467_ (
    .A1(_160_),
    .A2(_209_),
    .B1(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__lpflow_inputiso0n_1 _468_ (
    .A(_162_),
    .SLEEP_B(_174_),
    .X(_212_)
  );
  sky130_fd_sc_hd__a21oi_1 _469_ (
    .A1(_175_),
    .A2(_186_),
    .B1(_212_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor2_1 _470_ (
    .A(_164_),
    .B(_167_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__maj3_1 _471_ (
    .A(_163_),
    .B(_168_),
    .C(_173_),
    .X(_215_)
  );
  sky130_fd_sc_hd__xnor2_1 _472_ (
    .A(_214_),
    .B(_215_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nor3_1 _473_ (
    .A(_178_),
    .B(_134_),
    .C(_183_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__maj3_1 _474_ (
    .A(_170_),
    .B(_171_),
    .C(_172_),
    .X(_218_)
  );
  sky130_fd_sc_hd__xnor2_1 _475_ (
    .A(_217_),
    .B(_218_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__xnor2_1 _476_ (
    .A(_216_),
    .B(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__xnor2_1 _477_ (
    .A(_213_),
    .B(_220_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand2b_1 _478_ (
    .A_N(_184_),
    .B(_185_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _479_ (
    .A(_184_),
    .SLEEP(_185_),
    .X(_223_)
  );
  sky130_fd_sc_hd__a21oi_1 _480_ (
    .A1(_176_),
    .A2(_222_),
    .B1(_223_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__xnor2_1 _481_ (
    .A(_221_),
    .B(_224_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__xor2_1 _482_ (
    .A(_211_),
    .B(_225_),
    .X(_226_)
  );
  sky130_fd_sc_hd__xor2_2 _483_ (
    .A(_207_),
    .B(_226_),
    .X(_227_)
  );
  sky130_fd_sc_hd__lpflow_inputiso0n_1 _484_ (
    .A(_207_),
    .SLEEP_B(_226_),
    .X(_228_)
  );
  sky130_fd_sc_hd__a21oi_2 _485_ (
    .A1(_203_),
    .A2(_227_),
    .B1(_228_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__lpflow_inputiso0n_1 _486_ (
    .A(_211_),
    .SLEEP_B(_225_),
    .X(_230_)
  );
  sky130_fd_sc_hd__inv_1 _487_ (
    .A(_220_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__maj3_1 _488_ (
    .A(_213_),
    .B(_231_),
    .C(_224_),
    .X(_232_)
  );
  sky130_fd_sc_hd__nand2b_1 _489_ (
    .A_N(_218_),
    .B(_217_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__maj3_1 _490_ (
    .A(_214_),
    .B(_215_),
    .C(_219_),
    .X(_234_)
  );
  sky130_fd_sc_hd__inv_1 _491_ (
    .A(_234_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nand2_1 _492_ (
    .A(_214_),
    .B(_215_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nor2_1 _493_ (
    .A(_236_),
    .B(_233_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__a21oi_1 _494_ (
    .A1(_233_),
    .A2(_235_),
    .B1(_237_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__xnor2_1 _495_ (
    .A(_232_),
    .B(_238_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__xor2_1 _496_ (
    .A(_230_),
    .B(_239_),
    .X(_240_)
  );
  sky130_fd_sc_hd__xnor2_1 _497_ (
    .A(_229_),
    .B(_240_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__xnor2_1 _498_ (
    .A(_203_),
    .B(_227_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nand2_1 _499_ (
    .A(_197_),
    .B(_198_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nand2_1 _500_ (
    .A(_196_),
    .B(_199_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__o21ai_0 _501_ (
    .A1(_196_),
    .A2(_243_),
    .B1(_244_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__xnor2_1 _502_ (
    .A(_190_),
    .B(_201_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nand3_1 _503_ (
    .A(_242_),
    .B(_245_),
    .C(_246_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__inv_1 _504_ (
    .A(_240_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _505_ (
    .A(_238_),
    .SLEEP(_232_),
    .X(_249_)
  );
  sky130_fd_sc_hd__nor2_1 _506_ (
    .A(_237_),
    .B(_249_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__or3_1 _507_ (
    .A(_229_),
    .B(_248_),
    .C(_250_),
    .X(_251_)
  );
  sky130_fd_sc_hd__nand2_1 _508_ (
    .A(_230_),
    .B(_239_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__o211ai_1 _509_ (
    .A1(_229_),
    .A2(_248_),
    .B1(_250_),
    .C1(_252_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__o211ai_1 _510_ (
    .A1(_241_),
    .A2(_247_),
    .B1(_251_),
    .C1(_253_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _511_ (
    .A(_251_),
    .SLEEP(_002_),
    .X(_255_)
  );
  sky130_fd_sc_hd__a21oi_1 _512_ (
    .A1(weight_valid),
    .A2(act_valid),
    .B1(out),
    .Y(_256_)
  );
  sky130_fd_sc_hd__a211oi_1 _513_ (
    .A1(_254_),
    .A2(_255_),
    .B1(_256_),
    .C1(rst),
    .Y(_001_)
  );
  (* src = "/work/hdl/synth_top.sv:37.5-47.8" *)
  sky130_fd_sc_hd__dfxtp_1 _514_ (
    .CLK(clk),
    .D(_000_),
    .Q(result_valid)
  );
  (* src = "/work/hdl/synth_top.sv:37.5-47.8" *)
  sky130_fd_sc_hd__dfxtp_1 _515_ (
    .CLK(clk),
    .D(_001_),
    .Q(out)
  );
endmodule
