// Generated by: GPT-4o (gpt-4o-2024-11-20)
// Date: 2026-04-26
// Prompt: MAC module — clk, rst (active-high sync), a/b 8-bit signed, out 32-bit signed accumulator

module mac (
    input  wire        clk,
    input  wire        rst,
    input  wire signed [7:0] a,
    input  wire signed [7:0] b,
    output reg  signed [31:0] out
);

    // BUG: plain 'always' with posedge — should be always_ff for synthesizable sequential logic
    always @(posedge clk) begin
        if (rst) begin
            out <= 32'sd0;
            $display("MAC reset"); // BUG: $display is non-synthesizable
        end else begin
            // BUG: 8-bit * 8-bit = 16-bit product; added to 32-bit reg without explicit sign extension
            out <= out + a * b;
        end
    end

    // BUG: initial block is non-synthesizable
    initial begin
        out = 32'sd0;
    end

endmodule
