// Generated by: Claude Sonnet 4.6
// Date: 2026-04-26
// Prompt: MAC module — clk, rst (active-high sync), a/b 8-bit signed, out 32-bit signed accumulator

module mac (
    input  logic              clk,
    input  logic              rst,
    input  logic signed [7:0] a,
    input  logic signed [7:0] b,
    output logic signed [31:0] out
);

    always_ff @(posedge clk) begin
        if (rst)
            out <= '0;
        else
            out <= out + 32'(signed'(a)) * 32'(signed'(b));
    end

endmodule
