SIM              = icarus
TOPLEVEL_LANG    = verilog
VERILOG_SOURCES  = $(PWD)/bnn_layer.sv
TOPLEVEL         = bnn_layer
MODULE           = test_bnn_layer
COMPILE_ARGS    += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
