SIM              = icarus
TOPLEVEL_LANG    = verilog
VERILOG_SOURCES  = $(PWD)/spi_slave.sv
TOPLEVEL         = spi_slave
MODULE           = test_spi_slave
COMPILE_ARGS    += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
