// Generated by: Claude Sonnet 4.6
// Date: 2026-05-10
// 4x4 binary-weight crossbar MAC unit
//
// Each clock cycle (when in_valid=1) computes:
//   out[j] = sum_i weight[i][j] * in[i]   for j = 0..3
//
// Weight encoding: 1-bit per cell, 1 = +1, 0 = -1
// Weights loaded one per cycle via weight_we / weight_row / weight_col / weight_val.
//
// Input:  4 x 8-bit signed
// Output: 4 x 16-bit signed (registered; valid one cycle after in_valid)

`timescale 1ns/1ps

module crossbar_mac (
    input  logic              clk,
    input  logic              rst,

    // Weight programming (one weight per cycle)
    input  logic              weight_we,
    input  logic [1:0]        weight_row,
    input  logic [1:0]        weight_col,
    input  logic              weight_val,   // 1 = +1, 0 = -1

    // Data inputs (8-bit signed)
    input  logic signed [7:0] in0, in1, in2, in3,
    input  logic              in_valid,

    // Outputs (16-bit signed, registered)
    output logic signed [15:0] out0, out1, out2, out3,
    output logic               out_valid
);

    // 4x4 weight register array [row][col]
    logic w [0:3][0:3];   // 1 = +1, 0 = -1

    // Weight load
    always_ff @(posedge clk or posedge rst) begin
        if (rst) begin
            for (int r = 0; r < 4; r++)
                for (int c = 0; c < 4; c++)
                    w[r][c] <= 1'b1;
        end else if (weight_we) begin
            w[weight_row][weight_col] <= weight_val;
        end
    end

    // Sign-extend inputs to 16 bits for safe arithmetic
    wire signed [15:0] x0 = $signed(in0);
    wire signed [15:0] x1 = $signed(in1);
    wire signed [15:0] x2 = $signed(in2);
    wire signed [15:0] x3 = $signed(in3);

    // Combinational dot-product for each output column
    wire signed [15:0] xs [0:3];
    assign xs[0] = x0;
    assign xs[1] = x1;
    assign xs[2] = x2;
    assign xs[3] = x3;

    logic signed [15:0] mac_comb [0:3];
    always_comb begin
        for (int j = 0; j < 4; j++) begin
            mac_comb[j] = 16'sd0;
            for (int i = 0; i < 4; i++)
                mac_comb[j] = mac_comb[j] + (w[i][j] ? xs[i] : -xs[i]);
        end
    end

    // Output register
    always_ff @(posedge clk or posedge rst) begin
        if (rst) begin
            out0 <= '0; out1 <= '0; out2 <= '0; out3 <= '0;
            out_valid <= 1'b0;
        end else if (in_valid) begin
            out0      <= mac_comb[0];
            out1      <= mac_comb[1];
            out2      <= mac_comb[2];
            out3      <= mac_comb[3];
            out_valid <= 1'b1;
        end else begin
            out_valid <= 1'b0;
        end
    end

endmodule
